/*
 * This file was generated by qdbusxml2cpp-fix version 0.8
 * Command line was: qdbusxml2cpp-fix -c DBusDockEntry -p dbusdockentry com.deepin.dde.daemon.dock.Entry.xml
 *
 * qdbusxml2cpp-fix is Copyright (C) 2016 Deepin Technology Co., Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSDOCKENTRY_H
#define DBUSDOCKENTRY_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

typedef QMap<quint32, QString> WindowDict;

/*
 * Proxy class for interface com.deepin.dde.daemon.Dock.Entry
 */
class DBusDockEntry: public QDBusAbstractInterface
{
    Q_OBJECT

    Q_SLOT void __propertyChanged__(const QDBusMessage& msg)
    {
        QList<QVariant> arguments = msg.arguments();
        if (3 != arguments.count())
            return;
        QString interfaceName = msg.arguments().at(0).toString();
        if (interfaceName != "com.deepin.dde.daemon.Dock.Entry")
            return;
        QVariantMap changedProps = qdbus_cast<QVariantMap>(arguments.at(1).value<QDBusArgument>());
        foreach(const QString &prop, changedProps.keys()) {
        const QMetaObject* self = metaObject();
            for (int i=self->propertyOffset(); i < self->propertyCount(); ++i) {
                QMetaProperty p = self->property(i);
                if (p.name() == prop) {
                    emit p.notifySignal().invoke(this);
                }
            }
        }
   }
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.dde.daemon.Dock.Entry"; }

public:
    DBusDockEntry(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DBusDockEntry();

    Q_PROPERTY(uint CurrentWindow READ currentWindow NOTIFY CurrentWindowChanged)
    inline uint currentWindow() const
    { return qvariant_cast< uint >(property("CurrentWindow")); }

    Q_PROPERTY(QString DesktopFile READ desktopFile NOTIFY DesktopFileChanged)
    inline QString desktopFile() const
    { return qvariant_cast< QString >(property("DesktopFile")); }

    Q_PROPERTY(QString Icon READ icon NOTIFY IconChanged)
    inline QString icon() const
    { return qvariant_cast< QString >(property("Icon")); }

    Q_PROPERTY(QString Id READ id NOTIFY IdChanged)
    inline QString id() const
    { return qvariant_cast< QString >(property("Id")); }

    Q_PROPERTY(bool IsActive READ isActive NOTIFY IsActiveChanged)
    inline bool isActive() const
    { return qvariant_cast< bool >(property("IsActive")); }

    Q_PROPERTY(bool IsDocked READ isDocked NOTIFY IsDockedChanged)
    inline bool isDocked() const
    { return qvariant_cast< bool >(property("IsDocked")); }

    Q_PROPERTY(QString Menu READ menu NOTIFY MenuChanged)
    inline QString menu() const
    { return qvariant_cast< QString >(property("Menu")); }

    Q_PROPERTY(QString Name READ name NOTIFY NameChanged)
    inline QString name() const
    { return qvariant_cast< QString >(property("Name")); }

    Q_PROPERTY(WindowDict WindowTitles READ windowTitles NOTIFY WindowTitlesChanged)
    inline WindowDict windowTitles() const
    { return qvariant_cast< WindowDict >(property("WindowTitles")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Activate(uint in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QStringLiteral("Activate"), argumentList);
    }

    inline QDBusPendingReply<> Check()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Check"), argumentList);
    }

    inline QDBusPendingReply<> HandleDragDrop(uint in0, const QStringList &in1)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0) << QVariant::fromValue(in1);
        return asyncCallWithArgumentList(QStringLiteral("HandleDragDrop"), argumentList);
    }

    inline QDBusPendingReply<> HandleMenuItem(uint in0, const QString &in1)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0) << QVariant::fromValue(in1);
        return asyncCallWithArgumentList(QStringLiteral("HandleMenuItem"), argumentList);
    }

    inline QDBusPendingReply<> NewInstance(uint in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QStringLiteral("NewInstance"), argumentList);
    }

    inline QDBusPendingReply<> PresentWindows()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("PresentWindows"), argumentList);
    }

    inline QDBusPendingReply<> RequestDock()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("RequestDock"), argumentList);
    }

    inline QDBusPendingReply<> RequestUndock()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("RequestUndock"), argumentList);
    }

Q_SIGNALS: // SIGNALS
// begin property changed signals
void CurrentWindowChanged();
void DesktopFileChanged();
void IconChanged();
void IdChanged();
void IsActiveChanged();
void IsDockedChanged();
void MenuChanged();
void NameChanged();
void WindowTitlesChanged();
};

namespace dde {
  namespace dock {
    typedef ::DBusDockEntry Entry;
  }
}
#endif
